version: "3.9"
services:
  discordbot:
    build: .
    restart: unless-stopped
    env_file:
     - CONFIG.env
    depends_on:
     - redisserver
  redisserver:
    build: redis-conf/
    restart: unless-stopped
  web:
    build: webserver/
    restart: unless-stopped
    depends_on:
     - redisserver
    ports:
     - "127.0.0.1:8141:8000"
